[global]
network_transport       L2
time_stamping           software
tx_timestamp_timeout    100
free_running            1
sanity_freq_limit       0
logMinDelayReqInterval  -3
priority1               128
[ptp-lis0]